version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Zipping the Lambda package"
      - zip -r lambda-package.zip ./ -x buildspec.yml
      - echo "Build completed"
  post_build:
    commands:
      - echo "Updating Lambda function code"
      - aws lambda update-function-code --function-name lambda_s3_manual_deployment_function --zip-file fileb://lambda-package.zip
      - echo "Updating Lambda function configuration"
      - aws lambda update-function-configuration --function-name lambda_s3_manual_deployment_function --handler lambda.handler
artifacts:
  files:
    - lambda-package.zip
